"""Poll completed OpenAI batches and ingest them into VisionLife outputs."""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any

from openai import OpenAI

from records import AnalysisRecord, analysis_record_to_dict
from services.dashboard_service import sync_result_to_dashboard
from services.sensitivity_service import detect_sensitive_result, protect_sensitive_result
from utils import ensure_directory, extract_exif_data


TERMINAL_BATCH_STATUSES = {"completed", "failed", "cancelled", "expired"}


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for batch polling and result ingestion."""
    parser = argparse.ArgumentParser(
        description="Poll an OpenAI batch job and ingest completed VisionLife results into the dashboard."
    )
    parser.add_argument("--batch-id", required=True, help="OpenAI batch id to monitor.")
    parser.add_argument(
        "--manifest-file",
        required=True,
        help="Path to the manifest generated by batch_setup.py.",
    )
    parser.add_argument(
        "--workspace-dir",
        default=None,
        help="Workspace directory for output artifacts. Defaults to the manifest parent workspace.",
    )
    parser.add_argument(
        "--dashboard-dir",
        default=None,
        help="Target dashboard directory. Defaults to ~/Documents/Life_Dashboard.",
    )
    parser.add_argument(
        "--poll-seconds",
        type=int,
        default=30,
        help="Polling interval while batch status is non-terminal.",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Check status once and exit instead of polling continuously.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest_path = Path(args.manifest_file).expanduser().resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    workspace_dir = (
        Path(args.workspace_dir).expanduser().resolve()
        if args.workspace_dir
        else manifest_path.parent.parent
    )
    dashboard_dir = (
        Path(args.dashboard_dir).expanduser().resolve()
        if args.dashboard_dir
        else Path.home() / "Documents" / "Life_Dashboard"
    )
    ensure_directory(workspace_dir / "batch")
    ensure_directory(workspace_dir / "results")
    ensure_directory(dashboard_dir)

    client = OpenAI()
    batch_id = args.batch_id

    while True:
        batch = client.batches.retrieve(batch_id)
        print(f"BATCH {batch.id} STATUS {batch.status}")

        if batch.status in TERMINAL_BATCH_STATUSES:
            report = ingest_batch_outputs(
                client=client,
                batch=batch,
                manifest=manifest,
                workspace_dir=workspace_dir,
                dashboard_dir=dashboard_dir,
            )
            print(json.dumps(report, indent=2))
            return

        if args.once:
            return

        time.sleep(args.poll_seconds)


def ingest_batch_outputs(
    *,
    client: OpenAI,
    batch: Any,
    manifest: dict[str, Any],
    workspace_dir: Path,
    dashboard_dir: Path,
) -> dict[str, Any]:
    """Download batch outputs, rebuild canonical results, and publish them."""
    batch_dir = ensure_directory(workspace_dir / "batch")
    result_dir = ensure_directory(workspace_dir / "results")
    manifest_items = {item["custom_id"]: item for item in manifest.get("items", [])}

    output_records: list[dict[str, Any]] = []
    error_records: list[dict[str, Any]] = []

    output_file_id = getattr(batch, "output_file_id", None)
    if output_file_id:
        output_path = batch_dir / f"{batch.id}_output.jsonl"
        _download_file(client, output_file_id, output_path)
        output_records = _load_jsonl(output_path)

    error_file_id = getattr(batch, "error_file_id", None)
    if error_file_id:
        error_path = batch_dir / f"{batch.id}_errors.jsonl"
        _download_file(client, error_file_id, error_path)
        error_records = _load_jsonl(error_path)

    dashboard_notes: list[str] = []
    saved_results: list[str] = []
    protected_bundles: list[str] = []
    skipped_items: list[dict[str, Any]] = []

    for record in output_records:
        custom_id = record.get("custom_id")
        manifest_item = manifest_items.get(custom_id)
        if manifest_item is None:
            skipped_items.append({"custom_id": custom_id, "reason": "missing_manifest_item"})
            continue

        parsed = _parse_batch_output_record(record)
        if parsed is None:
            skipped_items.append({"custom_id": custom_id, "reason": "no_structured_output"})
            continue

        result_payload = build_result_payload(manifest_item, parsed)
        result_json = analysis_record_to_dict(result_payload)
        sensitivity = detect_sensitive_result(result_payload)
        if sensitivity.sensitive:
            bundle_path = protect_sensitive_result(result_payload, dashboard_dir / "ID", sensitivity)
            protected_bundles.append(str(bundle_path))
            continue

        result_path = result_dir / f"{Path(manifest_item['source_path']).stem}.json"
        result_path.write_text(json.dumps(result_json, indent=2), encoding="utf-8")
        saved_results.append(str(result_path))

        dashboard_path = sync_result_to_dashboard(result_payload, dashboard_dir)
        dashboard_notes.append(str(dashboard_path))

    report = {
        "batch_id": batch.id,
        "status": batch.status,
        "output_records": len(output_records),
        "error_records": len(error_records),
        "saved_results": saved_results,
        "dashboard_notes": dashboard_notes,
        "protected_bundles": protected_bundles,
        "skipped_items": skipped_items,
        "error_items": error_records,
    }
    report_path = batch_dir / f"{batch.id}_ingest_report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return report


def build_result_payload(manifest_item: dict[str, Any], vision_result: dict[str, Any]) -> AnalysisRecord:
    """Reconstruct a canonical analysis record from the batch manifest and model output."""
    analysis_path = Path(manifest_item["analysis_path"])
    return AnalysisRecord.from_parts(
        source_path=manifest_item["source_path"],
        analysis_path=manifest_item["analysis_path"],
        media_type=str(manifest_item.get("media_type", "image")),
        transformed=bool(manifest_item.get("transformed", False)),
        notes=list(manifest_item.get("notes", [])),
        metadata=dict(manifest_item.get("metadata", {})),
        exif_data=manifest_item.get("exif_data") or extract_exif_data(analysis_path),
        vision_result=vision_result,
        web_enrichment=None,
    )


def _download_file(client: OpenAI, file_id: str, target_path: Path) -> None:
    content = client.files.content(file_id)
    body = getattr(content, "text", None)
    if callable(body):
        text = body()
    elif isinstance(body, str):
        text = body
    else:
        text = content.read().decode("utf-8")
    target_path.write_text(text, encoding="utf-8")


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _parse_batch_output_record(record: dict[str, Any]) -> dict[str, Any] | None:
    response = record.get("response")
    if not isinstance(response, dict):
        return None

    body = response.get("body")
    if not isinstance(body, dict):
        return None

    output_text = body.get("output_text")
    if isinstance(output_text, str) and output_text.strip():
        return _safe_parse_json_object(output_text)

    for item in body.get("output", []):
        if not isinstance(item, dict):
            continue
        for content in item.get("content", []):
            if not isinstance(content, dict):
                continue
            text_value = content.get("text")
            if isinstance(text_value, str) and text_value.strip():
                parsed = _safe_parse_json_object(text_value)
                if parsed is not None:
                    return parsed

    return None


def _safe_parse_json_object(value: str) -> dict[str, Any] | None:
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


if __name__ == "__main__":
    main()
